apiVersion: v1
kind: ServiceAccount
metadata:
  name: stratus-tiller
  namespace: stratus-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stratus-tiller-manager
  namespace: stratus-dev
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stratus-tiller-binding
  namespace: stratus-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stratus-tiller-manager
subjects:
- kind: ServiceAccount
  name: stratus-tiller
  namespace: stratus-dev
# GCP user account
- kind: User
  name: janedoe@jaguarlandrover.com
# Cloud IAM service account
#- kind: User
#  name: test-account@test-project-123456.google.com.iam.gserviceaccount.com
